### ISSUE TITLE
【依頼】ProtoSpace挙動確認	

### ISSUE THREAD

**Issue by Aryokonon** [Aryokonon/protospace-39415#1]
https://protospace-39415.onrender.com/

**Comment by shodai-ito** [comment]
@Aryokonon さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`ユーザー管理機能`**
- [x] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されていること**
不要な箇所に「こんにちは、〇〇さん」が表示されているため削除をお願いします。
<img width="425" alt="スクリーンショット 2023-09-07 9 20 15" src="https://github.com/Aryokonon/protospace-39415/assets/62537107/7fc7a078-8fcd-4b91-820d-089e53bd996a">

### **`一覧機能`**
- [ ] **プロトタイプ毎に、画像・プロトタイプ名・キャッチコピー・投稿者名の、4つの情報について表示できること**
投稿者名が二箇所ずつ表示されています。
左側に表示されている名前は不要なので削除しましょう。
<img width="1177" alt="スクリーンショット 2023-09-07 9 21 01" src="https://github.com/Aryokonon/protospace-39415/assets/62537107/82001042-55e3-41fe-a8c8-67c1e9452d20">

### **`詳細機能`**
- [x] **ログイン・ログアウトの状態に関わらず、プロダクトの情報（プロトタイプ名・投稿者・画像・ キャッチコピー・コンセプト）が表示されていること**
ログアウト中、投稿者名が表示されません。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Aryokonon** [comment]
@shodai-ito  様

レビューありがとうございます
承知しました

只今　仕事中で　19時以降家帰ったら送ります
